services:
  checkmate-db:
    image: mysql:8.0
    container_name: checkmate-mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: checkmate
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - checkmate-mysql:/var/lib/mysql
    networks:
      - checkmate-network

  checkmate-app:
    build:
      context: ./
      dockerfile: ./dockerfile
    container_name: checkmate-app
    ports:
      - "3000:3000"
    environment:
      DB_URL: "mysql://root:root_password@localhost:3306/checkmate"
      NODE_ENV: development
      APP_DIR: "/Users/yashmeena/Downloads"
      GOOGLE_CLIENT_ID: "19414076491-dok0sie19mvd7tbnou1443ugu4gpnqtk.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
    depends_on:
      - checkmate-db
    networks:
      - checkmate-network
    volumes:
      - /Users/yashmeena/Downloads/checkmate
      - /checkmate/node_modules


volumes:
  checkmate-mysql:
    name: checkmate_db

networks:
  checkmate-network:
