services:
  checkmate-db:
    image: mysql:8.0
    container_name: checkmate-db
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - checkmate-mysql:/var/lib/mysql
    networks:
      - checkmate-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u root -proot_password || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  checkmate-app:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: checkmate-app
    depends_on:
      checkmate-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: ${DOCKER_DB_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3000:3000
    networks:
      - checkmate-network
    command: >
      sh -c "yarn db:init && yarn build && yarn start"


volumes:
  checkmate-mysql:
    name: checkmate-db
  checkmate-app:
    name: checkmate-app

networks:
  checkmate-network:
    driver: bridge
